#ifndef GLOBALS_H
#define GLOBALS_H

#define FRAMERATE 30
#define COUNTDOWN 3
#define EEP_OFFSET 100
#define HIGHSCORE_ADDR EEPROM_STORAGE_SPACE_START + EEP_OFFSET
#define EEP_CHECK_ADDR EEPROM_STORAGE_SPACE_START + EEP_OFFSET - 1
#define EEP_CHECK_VALUE 1

#endif
